#!/bin/bash

# This file is part of QDecompiler.
#
# QDecompiler is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as 
# published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# QDecompiler is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with QDecompiler. If not, see <https://www.gnu.org/licenses/>.

# Remove temporary files
cd bin
rm temp.txt
cd ..
cd jars
cd libraries
rm temp.txt
cd ..
cd versions/client
rm temp.txt
cd ../..
cd saves
rm temp.txt
cd ../..
cd src/minecraft
rm temp.txt
cd ../..
cd tmp
rm temp.txt
cd ..
sleep 5

# Starting Decompilation
cd scripts
chmod a+x versionchoose
chmod a+x decompile
./versionchoose
sleep 5
./decompile

# Exit
sleep 2
exit