#!/bin/bash

# This file is part of QDecompiler.
#
# QDecompiler is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as 
# published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# QDecompiler is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with QDecompiler. If not, see <https://www.gnu.org/licenses/>.

# Prompt
echo "Are you sure you want to cleanup? It's unrecoverable."
PS3='Choose your desired decision: '
choices=("Yes" "No")
select chc in "${choices[@]}"; do
    case $chc in
        "Yes")
            echo ""
            echo "You chose Yes"
            sleep 2
            cd ../src/minecraft
            rm -r net
            rm -r com
            cd ../lib
            rm -r *
            cd ../jars
            cd libraries
            rm -r *
            cd ../saves
            mv 'GlowstoneDecompiler Testing World' ../'GlowstoneDecompiler Testing World'
            rm -r *
            mv ../'GlowstoneDecompiler Testing World' 'GlowstoneDecompiler Testing World'
            ;;
        "No")
            echo ""
            echo "You chose No"
            sleep 2
            exit
            ;;
        *) echo "invalid option $REPLY";;
    esac
done

# Exit
sleep 2
exit