#!/bin/bash

# This file is part of QDecompiler.
#
# QDecompiler is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as 
# published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# QDecompiler is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with QDecompiler. If not, see <https://www.gnu.org/licenses/>.

echo "If it fails, please check your Java installation. Or you don't have Minecraft."
sleep 5

# JAR
echo "Downloading JARs..."
chmod a+x misc/jardl
./misc/jardl
sleep 2

# Copying libraries from .minecraft
echo "Now it'll copy the needed libraries for Minecraft to work."
echo "This can take long, depending on your computer."
cd ../jars
cp -r ~/.minecraft/libraries/* libraries
cd ../scripts
chmod a+x misc/eclipsecp
./misc/eclipsecp
sleep 2

# Decompilation/deobfuscation process
cd ../bin

echo "Now it'll start deobfuscation."
echo "Please be patient, because it'll take long (like hours)."
java -Xms512M -Xmx4096M -cp SpecialSource-1.10.0.jar:*:. net.md_5.specialsource.SpecialSource --in-jar ../tmp/client.jar --out-jar ../tmp/deobf.jar --srg-in ../tmp/client.txt --kill-lvt
sleep 2

echo "Now it'll start decompilation."
java -Xms512M -Xmx4096M -jar cfr-0.152.jar ../tmp/deobf.jar --outputdir ../src/minecraft
sleep 2

echo "Removing unnecessary temporary files."
cd ../tmp
cp client.jar ../jars/versions/client/client.jar
rm -r *
cd ../src
rm summary.txt