#!/bin/bash

# This file is part of QDecompiler.
#
# QDecompiler is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as 
# published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# QDecompiler is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with QDecompiler. If not, see <https://www.gnu.org/licenses/>.

cd ../tmp

echo "Select these versions and enter below."
PS3='Choose your desired Minecraft version to decompile: '
choices=("19w36a" "1.20" "1.20.1" "23w31" "Exit")
select chc in "${choices[@]}"; do
    case $chc in
        "19w36a")
            echo ""
            echo "You chose 19w36a"
            sleep 2
            # mapping
            curl https://piston-data.mojang.com/v1/objects/f483c4aa381c8f935d7a010751f12eb19851659f/client.txt
            # jar
            curl https://piston-data.mojang.com/v1/objects/54a359d0b47818d85c61db79ec742f7fdab5b914/client.jar
            ;;
        "1.20")
            echo ""
            echo "You chose 1.20"
            sleep 2
            # mapping
            curl https://piston-data.mojang.com/v1/objects/a4cd9a97400f7ecfe4dba23e427549ebc5815d66/client.txt
            # jar
            curl https://piston-data.mojang.com/v1/objects/e575a48efda46cf88111ba05b624ef90c520eef1/client.jar
            ;;
        "1.20.1")
            echo ""
            echo "You chose 1.20.1"
            sleep 2
            # mapping
            curl https://piston-data.mojang.com/v1/objects/6c48521eed01fe2e8ecdadbd5ae348415f3c47da/client.txt
            # jar
            curl https://piston-data.mojang.com/v1/objects/0c3ec587af28e5a785c0b4a7b8a30f9a8f78f838/client.jar
            ;;
        "23w31a")
            echo ""
            echo "You chose 23w31a"
            sleep 2
            # mapping
            curl https://piston-data.mojang.com/v1/objects/1c17aca622d87e393aae115137dcfd570b9c5d7b/client.txt
            # jar
            curl https://piston-data.mojang.com/v1/objects/ca51bf36913a7333c055096a52a3a96fbdb11813/client.jar
            ;;
	    "Exit")
	        echo "You chose exit"
	        exit
	        ;;
        *) echo "invalid option $REPLY";;
    esac
done